version: '3.8'

services:
  bank-app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: bank-app:latest
    ports:
      - "8090:8090"
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 11111111
      POSTGRES_DB: bank-rest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
