#
# application.yml — главный конфигурационный файл Spring Boot.
security:
  encryption-key: YanaLatyshSecret
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-rest
    username: user1
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:/db/migration/changelog/changelog.xml
card-number-details:
  bank-bin: 537000
  number-length: 16
jwt:
  secret-key: U29tZVN1cGVyU2VjdXJlS2V5U3RyaW5nV2l0aEVuY3J5cHRpb24xMjM0NTY=
  expiration-ms: 86400000
server:
  port: 8090

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
